# WeatherPy
----

### Analysis
* As expected, the weather becomes significantly warmer as one approaches the equator (0 Deg. Latitude). More interestingly, however, is the fact that the southern hemisphere tends to be warmer this time of year than the northern hemisphere. This may be due to the tilt of the earth.
* There is no strong relationship between latitude and cloudiness. However, it is interesting to see that a strong band of cities sits at 0, 80, and 100% cloudiness.
* There is no strong relationship between latitude and wind speed. However, in northern hemispheres there is a flurry of cities with over 20 mph of wind.

---

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [40]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import json
import pandas as pd
import numpy as np
import requests
import time
import os
import pprint


# Import API key
# path = os.path.join('keys', 'api_keys.py')
# print(path)
# from path import api_keys
from api_keys import api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
# create manual "output_data" folder first
output_data_file = "output_data/cities01.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

## Generate Cities List

In [48]:
# List for holding lat_lngs and cities
# Create empty list to store later
lat_lngs = []
cities = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(low=-90.000, high=90.000, size=50)
lngs = np.random.uniform(low=-180.000, high=180.000, size=50)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

48

### Perform API Calls
* Perform a weather check on each city using a series of successive API calls.
* Include a print log of each city as it'sbeing processed (with the city number and city name).

In [51]:
url = "http://api.openweathermap.org/data/2.5/weather?"

keep_cities = []
cloudiness = []
countries = []
date = []
humidity = []
lat = []
lng = []
max_temp = []
wind = []

for city in cities:
    query_url = f"{url}appid={api_key}&q={city}"
    weather_response = requests.get(query_url)
    weather_json = weather_response.json()
    try:
        keep_cities.append(weather_json['name'])
        cloudiness.append(weather_json['clouds']['all'])
        countries.append(weather_json['sys']['country'])
        date.append(weather_json['dt'])
        humidity.append(weather_json['main']['humidity'])
        lat.append(weather_json['coord']['lat'])
        lng.append(weather_json['coord']['lon'])
        max_temp.append(weather_json['main']['temp_max'])
        wind.append(weather_json['wind']['speed'])
    except:
        print(f"Skipping {city}.")
        continue

Skipping mutsamudu.
Skipping sinkat.
Skipping warqla.
Skipping samusu.
Skipping vaitupu.
Skipping illoqqortoormiut.

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

In [52]:
weather_dict = {
    "City": keep_cities,
    "Cloudiness": cloudiness,
    "Country": countries,
    "Date": date,
    "Humidity": humidity,
    "Lat": lat,
    "Lng": lng,
    "Max Temp": max_temp,
    "Wind Speed": wind,
}
weather_data = pd.DataFrame(weather_dict)
weather_data

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Tasiilaq,94,GL,1555635000,82,65.61,-37.64,276.150,7.20
1,Khani,81,GE,1555633800,100,41.96,42.96,281.150,0.50
2,Bintulu,90,MY,1555632000,94,3.17,113.03,298.150,0.59
3,Atuona,57,PF,1555636432,74,-9.80,-139.03,301.811,4.86
4,Morondava,0,MG,1555636857,70,-20.30,44.28,301.551,3.00
5,Vaini,0,IN,1555632000,33,15.34,74.49,296.150,3.10
6,Wanning,0,AT,1555636822,61,48.64,13.53,284.260,4.60
7,Butaritari,100,KI,1555636427,79,3.07,172.79,301.291,8.03
8,Vostok,32,RU,1555636858,36,46.45,135.83,273.101,6.75
9,Grand-Santi,64,GF,1555636858,97,4.27,-54.38,296.441,1.13
10,Ushuaia,75,AR,1555632000,69,-54.81,-68.31,275.150,3.60
11,Ardakan,75,IR,1555632000,28,32.31,54.02,296.150,5.10
12,Mataura,1,NZ,1555636205,58,-46.19,168.86,291.480,1.79
13,Cabatuan,1,PH,1555636858,75,16.95,121.67,300.171,1.62
14,Upernavik,58,GL,1555636423,98,72.79,-56.15,252.231,3.82
15,Port Alfred,4,ZA,1555636640,95,-33.59,26.89,289.820,3.76
16,Kumluca,100,TR,1555636858,86,36.37,30.29,275.601,2.11
17,Punta Arenas,75,CL,1555636394,81,-53.16,-70.91,280.150,8.20
18,Broken Hill,0,AU,1555632000,27,-31.97,141.45,299.150,7.20
19,Kathu,0,ZA,1555636547,59,-27.70,23.05,283.150,1.08
20,Tulun,77,RU,1555636859,39,54.56,100.58,267.791,9.13
21,Bredasdorp,0,ZA,1555636613,93,-34.53,20.04,287.590,2.10
22,Avarua,92,CK,1555633800,94,-21.21,-159.78,297.150,1.50
23,Bluff,0,AU,1555636670,49,-23.58,149.07,298.211,7.04
24,Finschhafen,98,PG,1555636859,74,-6.60,147.85,297.121,1.48
25,Barrow,95,AR,1555636859,49,-38.31,-60.23,293.611,2.55
26,Acapulco,0,MX,1555636859,62,16.86,-99.88,300.701,3.37
27,Ormara,0,PK,1555636859,55,25.21,64.64,297.861,1.56
28,Dikson,86,RU,1555636860,91,73.51,80.55,255.811,1.76
29,Jamestown,7,AU,1555636426,23,-33.21,138.60,300.931,6.17
30,Kortkeros,90,RU,1555636335,86,61.81,51.56,274.260,3.00
31,New Norfolk,20,AU,1555636636,62,-42.78,147.06,288.710,3.10
32,Busselton,100,AU,1555636534,96,-33.64,115.35,284.260,0.45
33,Manado,40,ID,1555635600,66,1.49,124.85,306.150,0.50
34,Cherskiy,92,RU,1555636860,89,68.75,161.30,265.911,8.68
35,Robore,20,BO,1555636860,71,-18.33,-59.76,298.301,1.84
36,Fare,2,PF,1555636860,77,-16.70,-151.02,302.111,5.14
37,Hithadhoo,73,MV,1555636860,77,-0.60,73.08,302.141,4.87
38,Totness,1,US,1555636811,73,33.74,-80.80,296.150,3.60
39,Tiksi,81,RU,1555636861,88,71.64,128.87,263.781,3.99
40,Lavrentiya,0,RU,1555636861,79,65.58,-170.99,258.221,4.42
41,Murgab,90,TM,1555632000,72,37.50,61.97,290.150,3.10

In [54]:
# save as csv
weather_data.to_csv("Output/weather_data.csv", index=False, header=True)

In [ ]:
# bubble_size = weather_data["temp"]

### Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

#### Latitude vs. Temperature Plot

#### Latitude vs. Humidity Plot

#### Latitude vs. Cloudiness Plot

#### Latitude vs. Wind Speed Plot